version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: athlete_dedup_db
    restart: unless-stopped
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: athlete_user
      POSTGRES_PASSWORD: athlete_pass
      POSTGRES_DB: athlete_dedup
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
